spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost


eureka:
          instance:
            preferIpAddress: true
          client:
            registerWithEureka: true
            fetchRegistry: true
            serviceUrl:
              defaultZone: http://34.211.218.205:8761/eureka/

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: true
spring.datasource.initialize : true

# H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2
# Datasource
spring.datasource.url: jdbc:h2:file:~/licensetest
spring.datasource.username: sa
spring.datasource.driver-class-name: org.h2.Driver
spring.jpa.show-sql: "true"
spring.datasource.validationQuery: "SELECT 1"