server:
  port: 8990

eureka:
          instance:
            preferIpAddress: true
          client:
            registerWithEureka: true
            fetchRegistry: true
            serviceUrl:
              defaultZone: http://54.191.33.84:8761/eureka/

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: true
spring.datasource.initialize : true